In [1]:
import pandas as pd
Future_CSCO = pd.read_csv("CSCO_Future_Data.csv", date_parser=True)

Predicted_CSCO = pd.read_csv("CSCO_Predicted_Data.csv", date_parser=True)
Predicted_CSCO

     Unnamed: 0        Date      Close    Adj Date  Predicted Close     Error
0           974  2019-10-01  47.740002  2019-09-24        49.933598  2.193596
1           975  2019-10-02  46.560001  2019-09-25        49.889220  3.329220
2           976  2019-10-03  47.060001  2019-09-26        49.707676  2.647675
3           977  2019-10-04  47.520000  2019-09-27        49.395260  1.875260
4           978  2019-10-07  47.770000  2019-09-30        49.086540  1.316540
..          ...         ...        ...         ...              ...       ...
280        1254  2020-11-09  38.200001  2020-11-02        37.911920 -0.288082
281        1255  2020-11-10  38.720001  2020-11-03        37.970850 -0.749149
282        1256  2020-11-11  39.330002  2020-11-04        38.062244 -1.267758
283        1257  2020-11-12  38.669998  2020-11-05        38.221170 -0.448829
284        1258  2020-11-13  41.400002  2020-11-06        38.415318 -2.984684

[285 rows x 6 columns]

In [2]:
Predicted_CSCO["Predicted_Close"]=Predicted_CSCO["Predicted Close"]

In [5]:
Predicted_CSCO=Predicted_CSCO.drop("Predicted Close", axis = 1)

In [8]:
Total_CSCO = pd.concat([Predicted_CSCO,Future_CSCO])

In [9]:
Total_CSCO.to_csv("Total_CSCO.csv")